config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :permits do
    get "approve", to: "permits#approve"
    get "reject", to: "permits#reject"
    get "request_approval", to: "permits#request_approval"
    patch "submit_request", to: "permits#submit_request"
    get "recall", to: "permits#recall"
  end
  resources :users, except: [:index]
  get "dashboard", to: "permits#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :authored_permits, class_name: "Permit", foreign_key: "author_id", dependent: :destroy
  has_many :approved_permits, class_name: "Permit", foreign_key: "approver_id", dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  include PgSearch
  multisearchable against: [:email, :first_name, :last_name, :role]

  def fullname
    first_name.capitalize + " " + last_name.capitalize
  end

  def short_first_name
    "#{first_name[0].capitalize}. #{last_name.capitalize}"
  end

  def short_last_name
    "#{first_name.capitalize} #{last_name[0].capitalize}"
  end

  def initials
    "#{first_name[0].capitalize}#{last_name[0].capitalize}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def show
    authorize @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(update_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:approver, :author, :admin)
  end

  def update_params
    params.require(:user).permit(:password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<h1>Edit your profile here</h1>

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Change password" %>
  </div>
<% end %>

<%= link_to "Back", user_path(@user) %>

app/views/users/show.html.erb
<div class="container col-9 user-page" style="padding-top: 8vh">
  <div class="return">
    <%= link_to "Back to your dashboard", permits_path, class: "btn-emerald-header user-btn"%>
    <% if @user == current_user %>
      <%= link_to "Change my password", edit_user_path(@user), class: "btn-emerald-header user-btn"%>
    <% end %>
  </div>
  <div class="user-info">
    <img class="user-img" src=<%= @user.avatar %> alt="avatar">
    <div class="user-text">
      <h2><%= @user.first_name %> <strong><%= @user.last_name %></strong></h2>
      <p><%= @user.role %></p>
      <hr>
      <div class="content-around">
        <div class="titles">
          <p>Phone number: </p>
          <p>Email: </p>
          <p>Role: </p>
          <p>Location: </p>
        </div>
        <div class="info">
          <p><%= @user.phone %></p>
          <p><%= @user.email %></p>
          <p><%= @user.role %></p>
          <p>London</p>
          <% if @user.approver %>
            <p class="approver">Permit approver</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>