config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :permits do
    get "approve", to: "permits#approve"
    get "reject", to: "permits#reject"
    get "request_approval", to: "permits#request_approval"
    patch "submit_request", to: "permits#submit_request"
    get "recall", to: "permits#recall"
  end
  resources :users, except: [:index]
  get "dashboard", to: "permits#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_confirmation.html.erb
<div class="selected-section" data-id="4">
  <div class="container">
    <div class="excavation center-detail container-permit-details">

      <div class="details">
        <div>
          <p><strong>Cat Scanner model:</strong></p>
          <p><strong>Serial number:</strong></p>
          <p><strong>Genny model:</strong></p>
          <p><strong>Serial number:</strong></p>
          <p><strong>Operator:</strong></p>
        </div>
        <div class="detail-info">
          <p><%= @permit.cat_scan_model %></p>
          <p><%= @permit.cat_scanner_serial %></p>
          <p><%= @permit.genny_model %></p>
          <p><%= @permit.genny_serial %></p>
          <p><%= @permit.cat_genny_operator %></p>
        </div>
      </div>

      <p class="center-text"><strong>Modes used:</strong></p>
      <div class="mechanical-dig center-detail">
        <% if @permit.cat_mode_power == true %>
          <p class="tag">Power</p>
          <% else %>
        <% end %>
        <% if @permit.cat_mode_radio == true %>
          <p class="tag">Radio</p>
        <% end %>
        <% if @permit.cat_mode_transmitter == true %>
          <p class="tag">Transmitter</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_excavation_dimensions.html.erb
<div class="selected-section" data-id="2">
  <div class="container">
    <div class="excavation center-detail move">
      <div class="permit-images">
        <%= image_tag("dimension.jpg") %>
        <%= image_tag("dimension2.jpg") %>
      </div>
      <p class="width">xwidth: <strong><%= @permit.xwidth %>mm</strong></p>
      <p class="depth">xdepth: <strong><%= @permit.xdepth %>mm</strong></p>
      <p class="length">xlength: <strong><%= @permit.xlength %>m</strong></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<script>
  const hideMessage = () => {
    const message = document.querySelector(".alert");
    message.style.display = "none";
  }
  setTimeout(function () {
    hideMessage();
  }, 5000);
</script>

app/views/shared/_index_cards_approver.html.erb
<div class="my-perm-index">
  <div class="index-cards">
    <% if @pending_permits.present? %>
      <% @permits.each do |permit| %>
        <% if permit.who_with == current_user %>
        <%= link_to permit_path(permit) do %>
          <div class="permit-card">
            <div class="permit-sections">
              <div class="card-top">
              <p class="charcoal"><%= permit.permit_number %></p>
              <h2 class="charcoal"><%= permit.title %></h2>
              </div>
              <div class="card-mid">
                <div class="permit-type-container">
                  <%= image_tag (permit.permit_type_img), class: "permit-type-img" %>
                </div>
              </div>
              <div class="icons-container">
                <span class="charcoal text-status"><%= permit.status.capitalize %></span>
                <div class="img-tooltip">
                  <%= image_tag((permit.author.avatar), class: "avatar-sml avatar-card-permit")%>
                  <span class="tooltip-text">author <%= permit.author.short_last_name %></span>
                </div>
              </div>
              <div class="card-bottom">
                <div>
                  <p class="grey-light"><span class="charcoal">Valid:</span>  <%= permit.date_time(permit.start_date) %> <span class="charcoal">to</span> <%= permit.date_time(permit.end_date) %></p>
                  <p class="validity"></p>
                </div>
                <%= link_to 'Archive', permit_path(permit[:id]), method: :delete, data: { confirm: "Archive permit... are you sure?" }, class: "archive-btn" %>
              </div>
            </div>
          </div>
        <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div class="nothing-card">
        <h5>No actions</h5>
        <hr>
        <i class="fas fa-clipboard-check"></i>
      </div>
    <% end %>
  </div>
</div>

<style>
  .my-perm-index {
    display: flex;
    overflow: auto;
  }
</style>

app/views/shared/_index_cards_author.html.erb
<div class="my-perm-index">
  <div class="index-cards">
    <% if @permits.present? %>
      <% @permits.each do |permit| %>
        <%= link_to permit_path(permit) do %>
          <div class="permit-card">
            <div class="permit-sections">
              <div class="card-top">
              <p class="charcoal"><%= permit.permit_number %></p>
              <h2 class="charcoal"><%= permit.title %></h2>
              </div>
              <div class="card-mid">
                <div class="permit-type-container">
                  <%= image_tag (permit.permit_type_img), class: "permit-type-img" %>
                </div>
              </div>
              <div class="icons-container">
                <span class="charcoal text-status"><%= permit.status.capitalize %></span>
                <!-- <i class="icon-status <%= permit.status_icon %>"></i> -->
                <div class="img-tooltip">
                  <% if permit.approver.present? %>
                  <%= image_tag((permit.approver.avatar), class: "avatar-sml avatar-card-permit")%>
                  <% end %>
                  <span class="tooltip-text">approver <%= permit.approver.short_last_name %></span>
                </div>
              </div>
              <div class="card-bottom">
                <div>
                  <p class="grey-light"><span class="charcoal">Valid:</span>  <%= permit.date_time(permit.start_date) %> <span class="charcoal">to</span> <%= permit.date_time(permit.end_date) %></p>
                  <p class="validity"></p>
                </div>
                <%= link_to 'Archive', permit_path(permit[:id]), method: :delete, data: { confirm: "Archive permit... are you sure?" }, class: "archive-btn" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="nothing-card">
        <h5>No actions</h5>
        <hr>
        <i class="fas fa-clipboard-check"></i>
      </div>
    <% end %>
  </div>
</div>

<style>
  .my-perm-index {
    display: flex;
    overflow: auto;
  }
</style>

app/views/shared/_index_cards_worker.html.erb
<% if @permits.size > 10000 %>
  <P>TODO</P>
<% else %>
  <div class="nothing-card">
        <h5>No briefings scheduled</h5>
        <hr>
        <i class="fas fa-clipboard-check"></i>
      </div>
<% end %>

app/views/shared/_index_table_worker.html.erb
<div class="filter-row">
    <button class="btn btn-green2"><%= link_to "All permits", dashboard_path %></button>
    <button class="btn btn-green2"><%= link_to "Previous breifings", dashboard_path %></button>
  </div>
<div style="overflow: scroll">
  <table class="table table-hover" id="permit-table">
    <thead>
      <tr>
        <th scope="col">Permit ID</th>
        <th scope="col">Title</th>
        <th scope="col">Type</th>
        <th scope="col">Start-date</th>
        <th scope="col">Exp-date</th>
        <th scope="col">Author</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @all_permits[0..9].each do |permit| %>
        <%= link_to permit_path(permit) do %>
          <tr>
              <td scope="row"> <%= link_to permit.permit_number, permit_path(permit) %></td>
              <td> <%= permit.title %> </td>
              <td> <%= permit.permit_type.capitalize %> </td>
              <td> <%= permit.short_date(permit.start_date) %> </td>
              <td> <%= permit.short_date(permit.end_date) %> </td>
              <td> <%= permit.author.first_name[0] + " " + permit.author.last_name %> </td>
              <td> <%= permit.status.capitalize %> </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="index-btm">
  <p>Show more</p>
</div>

app/views/shared/_mechanical_dig.html.erb
<div class="selected-section" data-id="5">
  <div class="container">
    <div class="mechanical-dig center-detail">
      <% @permit.attributes.to_a[(25..33)].each do |ele| %>
        <% if ele[1] == true %>
          <p class="tag"><%= ele[0].gsub(/_/, " ").capitalize %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="lhs">
    <!-- <a class="navbar-brand"> -->
      <%= link_to dashboard_path do %>
        <%= image_tag(("logo-emerald-lrg-bright.png"), class: "emerald-logo") %>
      <% end %>
    <!-- </a> -->
    <% unless current_user %>
      <%= link_to permits_path, class: "emerald-nav" do %>
        <h2>emerald</h2>
       <% end %>
       <% end %>
     <% if current_user %>
     <form class="form-search" method="get" id="s" action="/permits">
        <div class="input-append">
          <input type="text" class="input-medium search-query" name="s" placeholder="Search..." value="">
          <button type="submit" class="btn-emerald-header">Go</button>
        </div>
      </form>
      <% end %>
  </div>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">

          <div class="badge dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.approver == true && Permit.where(status: "pending approval").where(approver_id: current_user.id).size > 0 %>
              <p class="badge-num"><%= Permit.where(status: "pending approval").where(approver_id: current_user.id).size %></p>
            <% end %>
            <img class="avatar dropdown-toggle" src="<%= current_user.avatar %>" />

          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
  <div>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-invisible" %>
    </div>
  <% end %>
</div>

app/views/shared/_new_permits.html.erb
<%= simple_form_for @permit do |f| %>
  <%= f.input :title %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :permit_type %>
  <%= f.input :level %>
  <%= f.input :location %>
  <%= f.input :project_id %>
  <%= f.input :permit_number %>
  <%= f.input :method_statement %>
  <%= f.input :xwidth %>
  <%= f.input :xlength %>
  <%= f.input :xdepth %>
  <%= f.input :gas %>
  <%= f.input :fibre_optic %>
  <%= f.input :water %>
  <%= f.input :unknown %>
  <%= f.input :hv_electricity %>
  <%= f.input :bt %>
  <%= f.input :traffic_signal %>
  <%= f.input :signal_cable %>
  <%= f.input :lv_electricity %>
  <%= f.input :drains %>
  <%= f.input :street_lighting %>
  <%= f.input :no_services %>
  <%= f.input :hand_digging %>
  <%= f.input :confirm_work_package_plan %>
  <%= f.input :confirm_machine_operator %>
  <%= f.input :services_protected %>
  <%= f.input :exlusion_zone %>
  <%= f.input :buried_cables_identified %>
  <%= f.input :drawing_updated %>
  <%= f.input :physical_barrier_available %>
  <%= f.input :excavation_undermining_foundations %>
  <%= f.input :project_manager_phone %>
  <%= f.input :cat_scan_model %>
  <%= f.input :genny_model %>
  <%= f.input :calibration_expires %>
  <%= f.input :cat_scanner_serial %>
  <%= f.input :genny_serial %>
  <%= f.input :cat_genny_operator %>
  <%= f.input :cat_mode_power %>
  <%= f.input :cat_mode_radio %>
  <%= f.input :cat_mode_transmitter %>
  <%= f.input :works_description %>
  <%= f.input :approver_id, collection: User.where(approver: true), label_method: :fullname %>
  <%= f.button :submit, value: "Save & Exit" %>
  <%= link_to "Exit without saving", dashboard_path %>
<% end %>

app/views/shared/_permit_details.html.erb
<div class="selected-section show-section" data-id="1">
  <div class="container-permit-details center-detail">
    <p class="center-text">Permit reference: <%= @permit.permit_number %></p>
    <h2 class="center-text"><%= @permit.title %></h2>
    <div class="two-grid center-text">
      <p><strong>Work starts:</strong> <span class="begin"><%= @permit.start_date.strftime("%d-%m-%Y") %> <%= @permit.start_date.strftime("%I:%M%P") %></span></p> <p><strong>Expires:</strong> <span class="end"><%= @permit.end_date.strftime("%d-%m-%Y") %> at <%= @permit.end_date.strftime("%I:%M%P") %></span></p>
    </div>
    <!-- To be deleted when js logic is made -->
    <p class="center-text">Expires in xxx days</p>
    <% if @permit.status == "draft" %>
      <p class="center-text status-show"><i><strong>DRAFT</strong></i></p>
    <% elsif @permit.status == "pending approval" %>
      <p class="center-text status-show">Awaiting approval from <strong><%= @approver %></strong></p>
    <% elsif @permit.status == "approved" %>
      <p class="center-text status-show">Approved by: <strong><%= @approver %></strong></p>
    <% elsif @permit.status == "rejected" %>
      <p class="center-text status-show">Permit rejected by: <strong><%= @approver %></strong></p>
    <%# elsif @permit.status == "expired" %>
      <!-- <p><strong>Permit expired</strong></p> -->
    <% end %>

    <div class="details">
      <div>
        <p><strong>Project ID:</strong></p>
        <p><strong>Level:</strong></p>
        <p><strong>Location:</strong></p>
        <p><strong>Method Statement:</strong></p>
        <p><strong>Permit Type:</strong></p>
      </div>
      <div class="detail-info">
        <p><%= @permit.project_id %></p>
        <p><%= @permit.level %></p>
        <p><%= @permit.location %></p>
        <p><%= @permit.method_statement %></p>
        <p><%= @permit.permit_type %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_results.html.erb
<%= link_to permits_path do %>
  <h4 id="results-back"><i class="fas fa-arrow-left" id="results-back"></i> Search Results</h4>
<% end %>
<% if @search_permits.size.positive? %>
  <h4>Permits found (<%= @search_permits.size %>)</h4>
  <hr style="color: $grey-lighter">
  <div class="my-perm-index">
      <div class="index-cards">
        <% @search_permits.each do |permit| %>
          <%= link_to permit_path(permit) do %>
            <div class="permit-card">
            <div class="permit-sections">
              <div class="card-top">
              <p class="charcoal"><%= permit.permit_number %></p>
              <h2 class="charcoal"><%= permit.title %></h2>
              </div>
              <div class="card-mid">
                <div class="permit-type-container">
                  <%= image_tag (permit.permit_type_img), class: "permit-type-img" %>
                </div>
              </div>
              <div class="icons-container">
                <span class="charcoal text-status"><%= permit.status.capitalize %></span>
                <!-- <i class="icon-status <%= permit.status_icon %>"></i> -->
                <div class="img-tooltip">
                  <%= image_tag((permit.author.avatar), class: "avatar-sml avatar-card-permit")%>
                  <span class="tooltip-text">author <%= permit.author.short_last_name %></span>
                </div>
              </div>
              <div class="card-bottom">
                <div>
                  <p class="grey-light"><span class="charcoal">Valid:</span>  <%= permit.date_time(permit.start_date) %> <span class="charcoal">to</span> <%= permit.date_time(permit.end_date) %></p>
                  <p class="validity"></p>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>
<% else %>
<h4>Nothing found!</h4>
<p>Please re-do search or click "Search Results" to go back</p>
<% end %>

<% if @search_users.size.positive? %>
  <h4>People found (<%= @search_users.size %>)</h4>
  <hr style="color: $grey-lighter">
  <div class="my-perm-index">
      <div class="index-cards" id="person-cards">
            <div class="user-card">
               <% @search_users.each do |user| %></%>
                  <%= link_to user_path(user) do %>
                    <div class="left-card">
                      <img class="card-pic" style="background-image: url(<%= user.avatar %>);" alt="">
                    </div>
                    <div class="right-card">
                      <%= user.first_name %> <%= user.last_name %>
                      <hr>
                      <%= user.role %>
                    </div>
                  <% end %>
                <div class="card-email">
                  <%= link_to user.email %>
                </div>
            </div>
          <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_status_bar.html.erb
<div class="status-container">
  <div class="icons">
    <div class="draft">
      <p class="status-text">Draft</p>
      <i class="fas fa-circle status-inactive"></i>
      <i class="fas fa-dot-circle status-active"></i>
      <i class="fas fa-check-circle status-inactive"></i>
    </div>
<!-- <i class="show fas fa-angle-double-right"></i> Chevrons? -->

    <div class="awaiting">
      <p class="status-text">Awaiting approval</p>
      <i class="fas fa-circle status-active"></i>
      <i class="fas fa-dot-circle status-inactive"></i>
      <i class="fas fa-check-circle status-inactive"></i>
      <i class="fas fa-times-circle"></i>
    </div>
<!-- <i class="show fas fa-angle-double-right"></i> Chevrons? -->

    <div class="approved">
      <p class="status-text">Approved</p>
      <i class="fas fa-circle status-active"></i>
      <i class="fas fa-check-circle status-inactive"></i>
    </div>
  </div>
</div>