config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :permits do
    get "approve", to: "permits#approve"
    get "reject", to: "permits#reject"
    get "request_approval", to: "permits#request_approval"
    patch "submit_request", to: "permits#submit_request"
    get "recall", to: "permits#recall"
  end
  resources :users, except: [:index]
  get "dashboard", to: "permits#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :approver, class_name: "User", optional: true

  include PgSearch
  multisearchable against: [:location, :level, :permit_number, :method_statement, :title, :author_last_name, :author_first_name, :approver_first_name, :approver_last_name, :author_email, :approver_email, :supervisor]

  def perm_statuses
    statuses = [
      "draft",
      "pending approval",
      "rejected",
      "approved",
      "expired"
    ]
    statuses
  end

  def perm_types
    permit_types = [
      "permit to dig",
      "permit to drill",
      "permit to work at height",
      "permit to load",
      "confined space permit",
      "hot work permit"
    ]
    permit_types
  end

  def approver_first_name
    approver.present? ? approver.first_name : ""
  end

  def approver_last_name
    approver.present? ? approver.last_name : ""
  end

  def author_last_name
    author.present? ? author.last_name : ""
  end

  def author_first_name
    author.present? ? author.first_name : ""
  end

  def approver_email
    approver.present? ? approver.email : ""
  end

  def author_email
    author.present? ? author.email : ""
  end

  def supervisor
    if author == User.where(email: "jonathan.reid@laminar.com")[0] && title == "Excavate trench for Culvert 2C - Box culvert drain"
      "Rod Davis"
    end
  end

  def permit_type_img
    if permit_type == "permit to dig"
      img_url = "dig.png"
    elsif permit_type == "permit to drill"
      img_url = "drill.png"
    elsif permit_type == "permit to work at height"
      img_url = "work_at_height.png"
    elsif permit_type == "permit to load"
      img_url = "load.png"
    elsif permit_type == "confined space permit"
      img_url = "confined_space.jpg"
    elsif permit_type == "hot work permit"
      img_url = "hot_works.png"
    else
      img_url = "logo-emerald-lrg-bright.png"
    end
    img_url
  end

  def short_date(date)
    date.strftime("%e %b %y")
  end

  def date_time(date)
    date.strftime("%-d-%-m-%y %H:%M")
  end

  def time(date)
    date.strftime("%H:%M")
  end

  def status_icon
    statuses = perm_statuses
    if status == statuses[0]
      icon = 'far fa-edit status-draft'
    elsif status == statuses[1]
      icon = 'far fa-clock status-pending'
    elsif status == statuses[2]
      icon = 'fas fa-times status-rejected'
    elsif status == statuses[3]
      icon = 'fas fa-check status-approved'
    elsif status == statuses[4]
      icon = 'fas fa-exclamation status-expired'
    end
    icon
  end

  def who_with
    statuses = perm_statuses
    if [statuses[0], statuses[2], statuses[3]].include?(status)
      with_who = author
    elsif status == statuses[1]
      with_who = approver
    else
      with_who = nil
    end
    with_who
  end
end

app/controllers/permits_controller.rb
class PermitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_permit, only: [:show, :destroy, :edit, :update]
  before_action :set_root_permit, only: [:request_approval, :submit_request, :recall, :approve, :reject]

  def index
    @permits = policy_scope(Permit).order(start_date: :asc)
    if params[:status].present? && params[:author_id].present?
      @all_permits = Permit.where(status: params[:status]).where(author: current_user)
    elsif params[:status].present? && params[:approver_id].present?
      @all_permits = Permit.where(status: params[:status]).where(approver: current_user)
    elsif params[:status].present?
      @all_permits = Permit.where(status: params[:status])
    else
      @all_permits = Permit.all
      @all_permits = Permit.all.order(created_at: :desc)
    end
    @pending_permits = Permit.where(status: "pending approval").where(approver_id: current_user.id).order(start_date: :asc)
    @approved_permits = Permit.where(status: "approved").where(approver_id: current_user.id).order(start_date: :asc)
    @rejected_permits = Permit.where(status: "rejected").where(approver_id: current_user.id).order(start_date: :asc)
    @draft_permits = Permit.where(status: "draft").where(approver_id: current_user.id).order(start_date: :asc)
    @edit_permits = Permit.where(status: "rejected").where(author_id: current_user.id).order(start_date: :asc)
    @edit_permits = Permit.where(status: "draft").where(author_id: current_user.id).order(start_date: :asc)

    if params[:s].present?
      PgSearch::Multisearch.rebuild(Permit)
      PgSearch::Multisearch.rebuild(User)
      results = PgSearch.multisearch(params[:s])
      @results = results.map { |result| result.searchable }
      @search_users = @results.select{ |r| r.respond_to? :first_name }
      @search_permits = @results.select{ |r| r.respond_to? :title }
    else
      @search_users = []
      @search_permits = []
    end
  end

  def show
    # @columns = Permit.column
    @author = "#{@permit.author_first_name.capitalize} #{@permit.author_last_name.capitalize}"
    @approver = "#{@permit.approver_first_name.capitalize} #{@permit.approver_last_name.capitalize}"
  end

  def new
    @permit = Permit.new
    authorize @permit
    @approvers = User.all.where(approver: true)
  end

  def create
    @permit = Permit.new(permit_params)
    @permit.author = current_user
    authorize @permit
    @permit.status = "draft"
    if @permit.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def self.statuses
    stasuses = ["draft", "rejected", "pending approval", "approved", "expired"]
    stasuses
  end

  def request_approval
  end

  def submit_request
    if params[:submit]
      @permit.status = "pending approval"
      @permit.update_attributes(permit_params)
    elsif params[:cancel]
      @permit.status = "draft"
    end
    if @permit.save
      redirect_to permit_path(@permit)
    else
      render :request_approval
    end
  end

  def recall
    @permit.status = "draft"
    @permit.save
    redirect_to dashboard_path
  end

  def approve
    @permit.status = "approved"
    @permit.save
    redirect_to permit_path(@permit)
  end

  def reject
    @permit.status = "rejected"
    @permit.save
    redirect_to permit_path(@permit)
  end

  def edit
  end

  def update
    @permit.update_attributes(permit_params)
    @permit.status = "draft"
    @permit.save
    redirect_to dashboard_path
  end

  def destroy
    @permit.delete
    redirect_to dashboard_path
  end

  private

  def set_permit
    @permit = Permit.find(params[:id])
    authorize @permit
  end

  def set_root_permit
    @permit = Permit.find(params[:permit_id])
    authorize @permit
  end

  def permit_params
    params.require(:permit).permit(Permit.column_names, :approver_id)
  end
end

app/views/permits/edit.html.erb
<div class="container col-7" style="margin-top: 25px; margin-bottom: 25px">
  <%= render 'shared/new_permits' %>
</div>

app/views/permits/index.html.erb
<div class="body-container">
<!-- <div class="container col-11"> -->
  <% if params[:s] %>
    <%= render 'shared/search_results' %>
  <% end %>
  <!-- top header with add button -->
  <%= render 'shared/index_top_section' %>

  <!-- cards - DONE -->
  <% if current_user.approver %>
    <%= render 'shared/index_cards_approver' %>
  <% elsif current_user.author %>
    <%= render 'shared/index_cards_author' %>
  <% elsif current_user.admin %>
  <% else %>
    <%= render 'shared/index_cards_worker' %>
  <% end %>
  <!-- table -->
  <% if current_user.admin %>
    <%= render 'shared/index_table_admin' %>
  <% elsif current_user.author %>
    <%= render 'shared/index_table_auth.html.erb' %>
  <% elsif current_user.approver %>
    <%= render 'shared/index_table_app.html.erb' %>
  <% else %>
    <%= render 'shared/index_table_worker.html.erb' %>
  <% end %>
<!-- </div> -->

<%= javascript_pack_tag "validity" %>

</div>

app/views/permits/new.html.erb
<div class="container col-6" style="padding-top: 30px; padding-bottom: 20px;">
  <h2 style="padding-bottom: 20px;">Create a new permit</h2>
  <%= render 'shared/new_permits' %>
</div>

app/views/permits/request_approval.html.erb
<div class="container col-4" style="margin-top: 20vh;">
  <%= simple_form_for @permit, url: permit_submit_request_path(@permit) do |f| %>
    <%= f.input :approver_id, collection: User.where(approver: true), label_method: :fullname, default: @permit.approver %>
    <div class="confirm-cancel" style="text-align:right;">
      <%= f.button :submit, value: "Cancel", name: "cancel", class: "reject-btn", style: "width:inherit;" %>
      <%= f.button :submit, value: "Confirm & Submit", name: "submit", class:"btn-green2"%>
    </div>
  <% end %>
</div>

app/views/permits/show.html.erb
<div class="body-container">
  <div class="show-cont">
  <div class="top-three-sections">
    <div class="important-details">
      <div class="title-section">
        <h3><%= @permit.permit_type.capitalize %></h3>
        <h5><%= @permit.title %></h5>
        <p class="light">Description of Work</p>
        <p><%= @permit.works_description %></p>
        <p class="light">Level</p>
        <p><%= @permit.level %></p>
        <p class="light">Location</p>
        <p><%= @permit.location %></p>
        <p class="light">Permit Number</p>
        <p><%= @permit.permit_number %></p>
        <p class="light">Method Statement Reference</p>
        <p><%= @permit.method_statement %></p>

        <hr style="margin: 8px 0;">
        <div class="show-buttons">
        <% if @permit.who_with == @permit.author %>
          <% if @permit.author == current_user %>
            <% if @permit.status != "approved"  %>
              <div><%= link_to "Submit for Approval", permit_request_approval_path(@permit), method: :get, class: "btn btn-show show-green" %></div>
            <% end %>
              <div><%= link_to "Edit", edit_permit_path(@permit), class: "btn btn-show show-" %></div>
              <div><%= link_to 'Archive', permit_path(@permit), method: :delete, data: { confirm: "Archiving permit... are you sure?" }, class: "btn btn-show show-red " %></div>
          <% end %>
        <% elsif @permit.who_with == @permit.approver %>
          <% if @permit.author == current_user %>
            <div><%= link_to 'Withdraw Request', permit_recall_path(@permit), method: :get, class: "btn btn-show" %></div>
          <% elsif @permit.approver == current_user %>
            <div><%= link_to 'Approve', permit_approve_path(@permit), class: "btn btn-show" %></div>
            <div><%= link_to 'Reject', permit_reject_path(@permit), class: "btn btn-show" %></div>
          <% end %>
        <% end %>
        </div>

      </div>

      <div class="status-section">
        <h5>Document Status</h5>
        <p class="light">Status</p>
        <p id="permit-status"><%= @permit.status.capitalize %></p>
        <p class="light">Workflow</p>
        <i id="icon1" class="fas fa-circle i-grey i-trans"></i>
        <i id="icon2" class="fas fa-circle i-grey i-trans"></i>
        <i id="icon3" class="fas fa-circle i-grey i-trans"></i>
        <i id="icon4" class="fas fa-circle i-grey i-trans"></i>
        <hr style="margin: 8px 0;">
        <h5>Document Validity</h5>
        <p class="light">Start Date</p>
        <p id="start-date"><%= @permit.date_time(@permit.start_date) %> hrs</p>
        <p class="light">Expiry Date</p>
        <p id="end-date"><%= @permit.date_time(@permit.end_date) %> hrs</p>
        <p class="light">Validity</p>
        <p id="validity"></p>
      </div>
    </div>


    <div class="main-content">
      <div id="section-1">
        <%= render "shared/all" %>
      </div>
    </div>
  </div>

  <hr>

  <div class="bottom-bar">
    <div class="workers">
      <div id="author-show" class="people-show">
        <img class="avatar perm-av" src="<%= @permit.author.avatar %>" alt="">
        <div>
          <p class="light">Author</p>
          <p><%= @permit.author.fullname %></p>
        </div>
      </div>
      <hr style="margin: 8px 0;">
      <div id="approver-show" class="people-show">
        <img class="avatar perm-av" src="<%= @permit.approver.avatar %>" alt="">
        <div>
          <p class="light">Approver</p>
          <p><%= @permit.approver.fullname %></p>
        </div>
      </div>
    </div>
    <div class="comment-section">
      <p><strong>Add a comment</strong></p>
      <form>
        <input id="comments" type="text">
        <input class="btn green-btn" id="comment-btn" type="submit" value="Submit">
      </form>
    </div>
    <div>
      <p id="post-head"><strong>Comments</strong></p>
      <div id="posted"></div>
    </div>
  </div>
  <% if @permit.site_layout_img %>
  <hr>
    <div>
      <h5>Location</h5>
      <%= image_tag((@permit.site_layout_img), class: "site-layout")%>
    </div>
  <% end %>
</div>
<div>
</div>



<%= javascript_pack_tag "workflow" %>

<script>
  const comment = document.getElementById('comments');
  const submit = document.getElementById('comment-btn');
  const posted = document.getElementById('posted');

  <% if @permit.status == 'rejected' %>
    posted.insertAdjacentHTML("beforeend", `<p id="my-text">Please confirm water in area</p>`);
  <% end %>

  submit.addEventListener('click', (event) => {
    event.preventDefault();
    <% if current_user.author %>
      posted.insertAdjacentHTML("beforeend", `<p id="my-text">${comment.value}</p>`);
      comment.value = "";
      setTimeout(typing, 4500);
    <% elsif current_user.approver %>
      posted.insertAdjacentHTML("beforeend", `<p id="my-text">${comment.value}</p>`);
      comment.value = "";
    <% end %>
  });

  const typing = () => {
    posted.insertAdjacentHTML("beforeend", "<p id='response'>Yes, men and equipment are off site</p>");
  };
</script>